# fly.toml app configuration file generated for yoke-films-api on 2023-10-14T01:29:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yoke-films-api"
primary_region = "cdg"

[http_service]
  internal_port = 3500
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
